# Generated by Django 4.1.1 on 2022-09-28 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('most_recent_raise', models.PositiveIntegerField(blank=True, null=True)),
                ('most_recent_valuation', models.PositiveIntegerField(blank=True, null=True)),
                ('known_total_funding', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('companies_funded', models.ManyToManyField(db_table='investments', related_name='investors', to='data_ingestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.UUIDField(default=uuid.uuid4)),
                ('last_title', models.CharField(blank=True, max_length=255)),
                ('group_start_date', models.DateField(blank=True, null=True)),
                ('group_end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ingestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLinkedinAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_names', to='data_ingestion.company')),
            ],
        ),
    ]
