# Generated by Django 4.1.1 on 2022-09-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employment',
            options={'ordering': ('person_id',)},
        ),
    ]
